server:
  port: 9100
#nacos配置公共属性
#db:
#  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
#  driver-class-name: com.mysql.jdbc.Driver
#  username: root
#  password: p@ssw0rd
#spring:
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
logging:
  level:
    io:
     seata: debug
