server:
  port:  8585
spring:
  application:
    name: gateway8585
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8488
      config:
        server-addr: 192.168.1.5:8488
    sentinel:
      transport:
        clientIp: localhost:8080
      #        file-extension: properties
#        prefix: mydataid
    #  profiles:
    #    active: dev
    gateway:
      routes:
        - id: authorize_service
          uri: http://192.168.1.5:9595
          predicates:
          - Path=/oauth/**
        - id: order_service
          uri: http://192.168.1.5:8000
          predicates:
          - Path=/order/{segment}
        - id: product_service
          uri: lb://product-service
          predicates:
          - Path=/product/{segment}
                  #          filters:
                    #           - CustomTest=false

#        - id: test_cookie_route
#        　匹配条件后路由目标地址，服务负载均衡
#          uri: lb://localhost:8000
#          predicates:　#匹配条件 断言之间是且关系
#            - After=2020-05-07T12:55:50.780+08:00
#             - Before=2020-05-07T12:55:50.780+08:00
#             - Between=2020-05-07T12:55:50.780+08:00,2020-05-07T24:55:50.780+08:00
#             - Cookie=shadow,pretty
#             - Host=
#             - Header=
#             - Method=
#             - Path=/order/{segment}
#             - Query=






