spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8488
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'