#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.111:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: p@ssw0rd
#seata:
#  enabled: true
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 192.168.1.14:8488
#      group: SEATA_GROUP
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.1.14:8488
#      namespace:
#management:
#  endpoints:
#    web:
#      exposure:
#        include:  '*'
#logging:
#  level:
#    io:
#      seata: debug