server:
  port: 9595
spring:
  application:
    name: authorize-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8488
    sentinel:
      transport:
        clientIp: localhost:8080
        port: 8719