server:
  port: 9000
#management:
#  endpoints:
#    web:
#      exposure:
#        include:  '*'
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true